Repository brain-tec/l10n-italy, pull requests merged in 2019-07, with the labels that each got.

#137 Syncing from upstream zeroincombenze/l10n-italy (10.0)
  l10n_it_ddt/__manifest__.py
  l10n_it_ddt/data/mail_template_data.xml
  l10n_it_ddt/egg-info/description.rst
  l10n_it_ddt/egg-info/history.rst
  l10n_it_ddt/models/sale.py
  l10n_it_ddt/models/stock.py
  l10n_it_ddt/models/stock_picking_package_preparation.py
  l10n_it_ddt/views/sale.xml
  l10n_it_ddt/views/stock_picking.xml
  l10n_it_ddt/views/stock_picking_package_preparation.xml
  l10n_it_ddt/wizard/ddt_from_picking.py
Labels: 10.0

#138 Syncing from upstream zeroincombenze/l10n-italy (7.0)
  .travis.yml
Labels: 7.0

#139 Syncing from upstream zeroincombenze/l10n-italy (10.0)
  README.rst
  base_multireport/README.rst
  base_multireport/__manifest__.py
  base_multireport/egg-info/history.rst
  base_multireport/egg-info/usage_detail.csv
  base_multireport/egg-info/usage_detail.rst
  base_multireport/i18n/it.po
  base_multireport/models/account_invoice.py
  base_multireport/models/ir_actions_report_xml.py
  base_multireport/report_account_invoice/report_invoice.xml
  base_multireport/report_account_invoice/report_invoice_lines.xml
  base_multireport/report_account_invoice/report_invoice_payment_dues.xml
  base_multireport/static/description/index.html
  base_multireport/views/ir_actions_report_xml_view.xml
  l10n_it_einvoice_base/README.rst
  l10n_it_einvoice_base/egg-info/history.rst
  l10n_it_einvoice_in/i18n/it.po
  l10n_it_einvoice_out/i18n/it.po
  l10n_it_einvoice_send2sdi/__manifest__.py
  l10n_it_einvoice_send2sdi/egg-info/history.rst
  l10n_it_einvoice_send2sdi/models/attachment.py
  l10n_it_ricevute_bancarie/README.rst
  l10n_it_ricevute_bancarie/__manifest__.py
  l10n_it_ricevute_bancarie/egg-info/descrizione.rst
  l10n_it_ricevute_bancarie/egg-info/features.csv
  l10n_it_ricevute_bancarie/egg-info/features.rst
  l10n_it_ricevute_bancarie/egg-info/history.rst
  l10n_it_ricevute_bancarie/egg-info/usage.rst
  l10n_it_ricevute_bancarie/models/riba.py
  l10n_it_ricevute_bancarie/models/riba_config.py
  l10n_it_ricevute_bancarie/riba_workflow.xml
  l10n_it_ricevute_bancarie/static/description/index.html
  l10n_it_ricevute_bancarie/views/riba_view.xml
  l10n_it_ricevute_bancarie/views/wizard_accreditation.xml
Labels: 10.0

#140 [bt#5439] XML Export der Rechnung (#5439)
  l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py
Labels: 7.0.project_le_111
